<a href="https://colab.research.google.com/github/vijaykalmani/Census-Income-Project/blob/main/Census_income.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Capstone Project on Census income

In [23]:
#Import Libraries
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

In [24]:
#Load Dataset
data = pd.read_csv('/content/census-income.csv')
data

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,annual-income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

## 1. Data Preprocessing

#### - Data Preprocessing - converting the raw data into a clean data set.
#### - Whenever the data is gathered from different sources it is collected in raw format which is not feasible for the analysis.
#### - Pre-processing refers to the transformations applied to your data before feeding it to the algorithm.
#### - In python, scikit-learn library has a pre-built functionality under sklearn.preprocessing

## Replacing ? with None

In [25]:
data=data.replace(' ?',np.nan)

## Remove all the rows that contain NA values

In [26]:
data=data.dropna()

In [27]:
data.head(3)

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,annual-income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K

## 2. Data Manipulation

### a) Extract the “education” column and store it in “census_ed” .

In [28]:
census_ed=data['education']
census_ed

0         Bachelors
1         Bachelors
2           HS-grad
3              11th
4         Bachelors
            ...
32556    Assoc-acdm
32557       HS-grad
32558       HS-grad
32559       HS-grad
32560       HS-grad
Name: education, Length: 32561, dtype: object

### b) Extract all the columns from “age” to “relationship” and store it in “census_seq”.

In [29]:
census_seq=data.iloc[:,0:8]
census_seq

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife
...,...,...,...,...,...,...,...,...
32556,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband
32558,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried
32559,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife

### c) Extract the column number “5”, “8”, “11” and store it in “census_col”.

In [30]:
census_col=data.iloc[:, [5,8,11]]
census_col

           marital-status   race  capital-loss
0           Never-married  White             0
1      Married-civ-spouse  White             0
2                Divorced  White             0
3      Married-civ-spouse  Black             0
4      Married-civ-spouse  Black             0
...                   ...    ...           ...
32556  Married-civ-spouse  White             0
32557  Married-civ-spouse  White             0
32558             Widowed  White             0
32559       Never-married  White             0
32560  Married-civ-spouse  White             0

[32561 rows x 3 columns]

### d) Extract all the male employees who work in state-gov and store it in “male_gov”.

In [41]:
filter1 = data["sex"]=="Male"
filter2 = data["workclass"]=="State-gov"
male_gov=data.loc[(filter1) & (filter2)]
male_gov

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,annual-income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
11,30,State-gov,141297,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0,0,40,India,>50K
34,22,State-gov,311512,Some-college,10,Married-civ-spouse,Other-service,Husband,Black,Male,0,0,15,United-States,<=50K
48,41,State-gov,101603,Assoc-voc,11,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
123,29,State-gov,267989,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,50,United-States,>50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32163,36,State-gov,135874,Bachelors,13,Married-civ-spouse,Sales,Husband,White,Male,0,0,40,United-States,<=50K
32241,45,State-gov,231013,Bachelors,13,Divorced,Protective-serv,Not-in-family,White,Male,0,0,40,United-States,<=50K
32321,54,State-gov,138852,HS-grad,9,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,40,United-States,<=50K
32324,42,State-gov,138162,Some-college,10,Divorced,Adm-clerical,Own-child,White,Male,0,0,40,United-States,<=50K
32360,58,State-gov,200316,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K

### e) Extract all the 39 year olds who either have a bachelor's degree or who are
### native of the United States and store the result in “census_us”.

In [42]:
filterAge = data["age"]==39
filterDegree = data["education"]=="Bachelors"
filterNative = data["native-country"]=="United-States"
census_us=data.loc[(filterAge)& ((filterDegree) | (filterNative))]
census_us

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,annual-income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
28,39,Private,367260,HS-grad,9,Divorced,Exec-managerial,Not-in-family,White,Male,0,0,80,United-States,<=50K
129,39,Private,365739,Some-college,10,Divorced,Craft-repair,Not-in-family,White,Male,0,0,40,United-States,<=50K
166,39,Federal-gov,235485,Assoc-acdm,12,Never-married,Exec-managerial,Not-in-family,White,Male,0,0,42,United-States,<=50K
320,39,Self-emp-not-inc,174308,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32146,39,Private,117381,Some-college,10,Divorced,Transport-moving,Not-in-family,White,Male,0,0,65,United-States,<=50K
32260,39,Federal-gov,232036,Some-college,10,Married-civ-spouse,Adm-clerical,Husband,White,Male,0,0,40,United-States,>50K
32428,39,Federal-gov,110622,Bachelors,13,Married-civ-spouse,Adm-clerical,Wife,Asian-Pac-Islander,Female,0,0,40,Philippines,<=50K
32468,39,Self-emp-not-inc,193689,HS-grad,9,Never-married,Exec-managerial,Not-in-family,White,Male,0,0,65,United-States,<=50K
32545,39,Local-gov,111499,Assoc-acdm,12,Married-civ-spouse,Adm-clerical,Wife,White,Female,0,0,20,United-States,>50K

### f) Extract 200 random rows from the “census” data frame and store it in “census_200”.

In [33]:
census_200=data.sample(n = 200)
census_200

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,annual-income
29132,50,Self-emp-not-inc,334273,Bachelors,13,Married-civ-spouse,Sales,Husband,White,Male,0,0,8,United-States,<=50K
19781,51,Private,147200,HS-grad,9,Never-married,Adm-clerical,Not-in-family,Black,Female,0,0,40,United-States,<=50K
11188,50,Private,135643,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Other-relative,Asian-Pac-Islander,Female,0,0,40,China,<=50K
20339,26,Private,157617,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,Poland,<=50K
7265,35,Private,192626,Some-college,10,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,50,United-States,>50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29167,20,Private,192711,Some-college,10,Never-married,Handlers-cleaners,Own-child,White,Female,0,0,40,United-States,<=50K
17294,41,Private,111483,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,45,United-States,<=50K
26403,25,Private,200318,HS-grad,9,Married-civ-spouse,Transport-moving,Husband,White,Male,0,0,60,United-States,<=50K
23747,19,Private,35865,Some-college,10,Never-married,Other-service,Not-in-family,White,Female,0,0,30,United-States,<=50K
30316,22,Private,251196,Some-college,10,Never-married,Protective-serv,Own-child,Black,Female,0,0,20,United-States,<=50K

### g) Get the count of different levels of the “workclass” column.

In [34]:
data['workclass'].value_counts()

workclass
Private             22696
Self-emp-not-inc     2541
Local-gov            2093
?                    1836
State-gov            1298
Self-emp-inc         1116
Federal-gov           960
Without-pay            14
Never-worked            7
Name: count, dtype: int64

### h) Calculate the mean of the “capital.gain” column grouped according to “workclass”.

In [35]:
data.groupby('workclass', as_index=False)['capital-gain'].mean()

          workclass  capital-gain
0                 ?    606.795752
1       Federal-gov    833.232292
2         Local-gov    880.202580
3      Never-worked      0.000000
4           Private    889.217792
5      Self-emp-inc   4875.693548
6  Self-emp-not-inc   1886.061787
7         State-gov    701.699538
8       Without-pay    487.857143

### i) Create a separate dataframe with the details of males and females from the census data that has income more than 50,000

In [49]:
filterMore = data["annual-income"]=='>50K'
second_data= data.loc[(filterMore)]
second_data

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,annual-income
7,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K
8,31,Private,45781,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States,>50K
9,42,Private,159449,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,5178,0,40,United-States,>50K
10,37,Private,280464,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0,0,80,United-States,>50K
11,30,State-gov,141297,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0,0,40,India,>50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32539,71,?,287372,Doctorate,16,Married-civ-spouse,?,Husband,White,Male,0,0,10,United-States,>50K
32545,39,Local-gov,111499,Assoc-acdm,12,Married-civ-spouse,Adm-clerical,Wife,White,Female,0,0,20,United-States,>50K
32554,53,Private,321865,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,>50K
32557,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32560,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

### j) Calculate the percentage of people from the United States who are private employees and earn less than 50,000 annually.

In [50]:
filterLess = data["annual-income"]=='<=50K'
filterUS = data["native-country"]=='United-States'
filterType = data["workclass"]=='Private'
third_data= data.loc[(filterLess)&(filterUS)&(filterType)]
result=len(third_data.index)/len(data.index)
result = "{:.0%}". format(result)
print(result)

48%

### k) Calculate the percentage of married people in the census data.

In [51]:
fourth_data= data.loc[(data["marital-status"]=='Married-spouse-absent')
                      |(data["marital-status"]=='Married-civ-spouse')|(data["marital-status"]=='Married-AF-spouse')]
fourth=len(fourth_data.index)/len(data.index)
secondresult = "{:.0%}". format(fourth)
print(secondresult)

47%

### l) Calculate the percentage of high school graduates earning more than 50,000 annually.

In [53]:
filterGrad = data["education"]=="HS-grad"
filterGreater50 = data["annual-income"]==">50K"
fifth_data= data.loc[(filterGrad)&(filterGreater50)]

fifth=len(fifth_data.index)/len(data.index)
fifthresult = "{:.0%}". format(fifth)
print(fifthresult)

5%

## Linear Regression:

### a) Build a simple linear regression model as follows:

###### ●	Divide the dataset into training and test sets in 70:30 ratio.
###### ●	Build a linear model on the test set where the dependent variable is “hours.per.week” and the independent variable is “education.num”.
###### ●	Predict the values on the train set and find the error in prediction.
###### ●	Find the root-mean-square error (RMSE).

In [54]:
df = data.copy()
df.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,annual-income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

#### LabelEncoder() - Encode target labels with value between 0 and n_classes-1.

In [55]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

#fit_transform(variable) -- Fit label encoder and return encoded labels.
df=df.apply(le.fit_transform)

In [56]:
df.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,annual-income
0,22,7,2671,9,12,4,1,1,4,1,25,0,39,39,0
1,33,6,2926,9,12,2,4,0,4,1,0,0,12,39,0
2,21,4,14086,11,8,0,6,1,4,1,0,0,39,39,0
3,36,4,15336,1,6,2,6,0,2,1,0,0,39,39,0
4,11,4,19355,9,12,2,10,5,2,0,0,0,39,5,0

In [57]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report


# get the locations (dependent variable is “hours.per.week” and the independent variable is “education.num”.)
X = data.iloc[:, -3]
y = data.iloc[:, -11]

# split the dataset in ratio of 70:30
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=0)

In [58]:
X.head()

0    40
1    13
2    40
3    40
4    40
Name: hours-per-week, dtype: int64

In [59]:
y.head()

0    13
1    13
2     9
3     7
4    13
Name: education-num, dtype: int64

#### model.fit() : fit training data. For supervised learning applications, this accepts two arguments: the data X and the labels y (e.g. model.fit(X, y)). For unsupervised learning applications, this accepts only a single argument, the data X (e.g. model.fit(X)).

In [60]:
X_train = np.array(X_train)
y_train = np.array(y_train)
linear = LinearRegression()
linear.fit(X_train.reshape(-1, 1), y_train)

LinearRegression()

In [61]:
#Predicting
X_train=np.array(X_train)
data_pred = linear.predict(X_train.reshape(-1, 1))
print("Predicated train data set = ",data_pred)

Predicated train data set =  [10.65301803  9.99236546 10.35272141 ... 10.05242479 10.2025731
 10.29266208]

In [62]:
# error  for model
y_test=np.array(y_train)
accuracy=linear.score(X_train.reshape(-1, 1), y_train)
err=1-accuracy
err = "{:.0%}". format(err)
print("Error in Prediction = ",err)

Error in Prediction =  98%

In [63]:
#Root mean square error
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_train, data_pred)
print("Root mean square error = ",mae)

Root mean square error =  1.9030184921217779

In [64]:
df.dtypes

age               int64
workclass         int64
fnlwgt            int64
education         int64
education-num     int64
marital-status    int64
occupation        int64
relationship      int64
race              int64
sex               int64
capital-gain      int64
capital-loss      int64
hours-per-week    int64
native-country    int64
annual-income     int64
dtype: object

In [65]:
df.head(5)

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,annual-income
0,22,7,2671,9,12,4,1,1,4,1,25,0,39,39,0
1,33,6,2926,9,12,2,4,0,4,1,0,0,12,39,0
2,21,4,14086,11,8,0,6,1,4,1,0,0,39,39,0
3,36,4,15336,1,6,2,6,0,2,1,0,0,39,39,0
4,11,4,19355,9,12,2,10,5,2,0,0,0,39,5,0

In [66]:
df.dtypes

age               int64
workclass         int64
fnlwgt            int64
education         int64
education-num     int64
marital-status    int64
occupation        int64
relationship      int64
race              int64
sex               int64
capital-gain      int64
capital-loss      int64
hours-per-week    int64
native-country    int64
annual-income     int64
dtype: object

## 4) Logistic Regression:

### a) Build a simple logistic regression model as follows:
###### ●	Divide the dataset into training and test sets in 65:35 ratio.
###### ●	Build a logistic regression model where the dependent variable is “X”(yearly income) and the independent variable is “occupation”.
###### ●	Predict the values on the test set.
###### ●	Build a confusion matrix and find the accuracy.

In [67]:
df.head(5)

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,annual-income
0,22,7,2671,9,12,4,1,1,4,1,25,0,39,39,0
1,33,6,2926,9,12,2,4,0,4,1,0,0,12,39,0
2,21,4,14086,11,8,0,6,1,4,1,0,0,39,39,0
3,36,4,15336,1,6,2,6,0,2,1,0,0,39,39,0
4,11,4,19355,9,12,2,10,5,2,0,0,0,39,5,0

In [68]:
X = df.iloc[:, -8]
y = df.iloc[:, -1]

y=y.astype('int')

# split the dataset in 65:35 ratio
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.35, random_state=0)

In [69]:
X.head()

0    1
1    0
2    1
3    0
4    5
Name: relationship, dtype: int64

In [70]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: annual-income, dtype: int64

In [72]:
df[['occupation']].value_counts()

occupation
10            4140
3             4099
4             4066
1             3770
12            3650
8             3295
7             2002
0             1843
14            1597
6             1370
5              994
13             928
11             649
9              149
2                9
Name: count, dtype: int64

In [73]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import mean_absolute_error, accuracy_score
X_test=np.array(X_test)
X_train=np.array(X_train)
logreg = LogisticRegression(solver='liblinear')
logreg.fit(X_train.reshape(-1, 1),y_train)
y_pred = logreg.predict(X_test.reshape(-1, 1))
print ("So, Our accuracy Score is: {}".format(round(accuracy_score(y_pred, y_test),4)))

So, Our accuracy Score is: 0.7579

In [74]:
# Creates a confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion matrix = \n",cm)

Confusion matrix =
 [[8638    0]
 [2759    0]]

### b) Build a multiple logistic regression model as follows:
###### ●	Divide the dataset into training and test sets in 80:20 ratio.
###### ●	Build a logistic regression model where the dependent variable is “X”(yearly income) and independent variables are “age”, “workclass”, and “education”.
###### ●	Predict the values on the test set.
###### ●	Build a confusion matrix and find the accuracy.

In [75]:
y = df.iloc[:, -1]
X = df.iloc[:, [0,1,3]]

y=y.astype('int')

# split the dataset  80:20 ratio
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=0)

In [76]:
X.head()

   age  workclass  education
0   22          7          9
1   33          6          9
2   21          4         11
3   36          4          1
4   11          4          9

In [77]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: annual-income, dtype: int64

In [78]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import mean_absolute_error, accuracy_score
X_test=np.array(X_test)
X_train=np.array(X_train)
logreg = LogisticRegression(solver='liblinear')
logreg.fit(X_train,y_train)\


y_pred = logreg.predict(X_test)

#y_pred = logreg.predict(X_test.reshape(-1, 1))
print ("So, Our accuracy Score is: {}".format(round(accuracy_score(y_pred, y_test),4)))

So, Our accuracy Score is: 0.7427

In [79]:
# Creates a confusion matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[4804  114]
 [1562   33]]

## 5) Decision Tree
### a) Build a decision tree model as follows:

###### ●	Divide the dataset into training and test sets in 70:30 ratio.
###### ●	Build a decision tree model where the dependent variable is “X”(Yearly Income) and the rest of the variables as independent variables.
###### ●	Predict the values on the test set.
###### ●	Build a confusion matrix and calculate the accuracy.

In [80]:
X = df.iloc[:, :-1]
y = df.iloc[:, -1]
#y=y.astype('int')

# split the dataset in 70:30 ratio
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=1)

In [81]:
X.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country
0,22,7,2671,9,12,4,1,1,4,1,25,0,39,39
1,33,6,2926,9,12,2,4,0,4,1,0,0,12,39
2,21,4,14086,11,8,0,6,1,4,1,0,0,39,39
3,36,4,15336,1,6,2,6,0,2,1,0,0,39,39
4,11,4,19355,9,12,2,10,5,2,0,0,0,39,5

In [82]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: annual-income, dtype: int64

In [83]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier()

dt.fit(X_train,y_train)
y_pred=dt.predict(X_test)

print('Confusion Matrix :')
print(confusion_matrix(y_pred,y_test))
print('Accuracy Score is : ',accuracy_score(y_test,y_pred))

Confusion Matrix :
[[6553  836]
 [ 997 1383]]
Accuracy Score is :  0.8123656464325929

## 6) Random Forest
### a) Build a random forest model as follows:
###### ●	Divide the dataset into training and test sets in 80:20 ratio.
######  ●	Build a random forest model where the dependent variable is “X”(Yearly Income) and the rest of the variables as independent variables and number of trees as 300.
######  ●	Predict values on the test set
######  ●	Build a confusion matrix and calculate the accuracy

In [84]:
X = df.iloc[:, :-2]
y = df.iloc[:, -1]

In [85]:
X.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week
0,22,7,2671,9,12,4,1,1,4,1,25,0,39
1,33,6,2926,9,12,2,4,0,4,1,0,0,12
2,21,4,14086,11,8,0,6,1,4,1,0,0,39
3,36,4,15336,1,6,2,6,0,2,1,0,0,39
4,11,4,19355,9,12,2,10,5,2,0,0,0,39

In [86]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: annual-income, dtype: int64

In [87]:
y.dtypes

dtype('int64')

In [88]:
from sklearn.ensemble import RandomForestClassifier

# split the dataset in 89:20
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=1)

rf=RandomForestClassifier(n_estimators=300)

rf.fit(x_train,y_train)

y_pred=rf.predict(x_test)

print('Confusion Matrix :')
print(confusion_matrix(y_pred,y_test))

print('Accuracy Score :',accuracy_score(y_test,y_pred))

Confusion Matrix :
[[4658  518]
 [ 368  969]]
Accuracy Score : 0.8639643789344388